name: Create Images

on:
  workflow_dispatch:
    inputs:
      artifactUrls:
        description: 'Comma-separated list of artifact URLs'
        required: true
        type: string

  workflow_call:
    inputs:
      artifactUrls:
        description: 'Comma-separated list of artifact URLs'
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      ACR_LOGIN_SERVER:
        required: true
      DBS_STORAGE_ACCOUNT:
        required: true

permissions:
  id-token: write
  contents: read

env:
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  DBS_STORAGE_ACCOUNT: ${{ secrets.DBS_STORAGE_ACCOUNT }}

jobs:
  prepare:
    runs-on: windows-2022
    outputs:
      matrix: ${{ steps.prepare.outputs.matrix }}
    steps:
      - name: Prepare matrix
        id: prepare
        uses: Freddy-DK/Fkh/.github/actions/create-image-prepare@main
        with:
          artifactUrls: ${{ inputs.artifactUrls }}

  build:
    needs: prepare
    runs-on: windows-2022
    strategy:
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}
      fail-fast: false
    steps:
      - name: Create BC Image
        uses: Freddy-DK/Fkh/.github/actions/create-image-build@main
        with:
          artifactUrl: ${{ matrix.artifactUrl }}
          acrLoginServer: ${{ env.ACR_LOGIN_SERVER }}
          dbsStorageAccount: ${{ env.DBS_STORAGE_ACCOUNT }}
          azureClientId: ${{ env.AZURE_CLIENT_ID }}
          azureTenantId: ${{ env.AZURE_TENANT_ID }}
          azureSubscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}


